### PR TITLE
SonarQube analysis

### PR DESCRIPTION
**Pull request by gquerret**
Example of SonarQube analysis with Gradle, report available at https://sonar2.riverside-software.fr/dashboard?id=adetran

One question, why is there [one xcode'd file](https://github.com/progress/adetran/blob/master/src/main/abl/adetran/common/_prtscrn.p)  in the repository ?

### CODE REVIEW

**Comment by gquerret** [comment]
PS: let me know if you don't want the report to be publicly available.

**Comment by zerovian** [comment]
This doesn't work "out of the box" without an install of sonarqube.  I'd ask you update the README.md with some description and/or create a wiki entry with requirements/steps of what the user would need to do to make this work and where they can find more information.

In addition, please add some comments to the build.gradle file indicating there are some external dependencies needed if you want to run the sonarqube task (as described in the README/wiki...).

**Comment by zerovian** [comment]
You're welcome to do whatever you want with the report.  The code is public so it isn't like we're hiding anything, and the disclaimer is there indicating it is unsupported.  Use at your own risk !!  if you want to submit fixes... no guarantees

I'll check on the xcoded file to see what needs to be done there.  What's the file name?

**Comment by zerovian** [comment]
I found the xcoded file from your link.

**Comment by zerovian** [comment]
won't pull. no response after a few weeks.

**Comment by gquerret** [comment]
> won't pull. no response after a few weeks.

I've opened the PR before going on holiday, sorry for the late answers.

> This doesn't work without a copy of SonarQube Installed

The point is to be able to push the results to any SonarQube server, not to execute it for every build. Your CI server should execute the Gradle script with an additional property sonar.host.url pointing to your own server. https://sonar2.riverside-software.fr is just provided as an example.
Adetran might not be the best project for a SonarQube example, but it's the first Gradle / Latte that I see !

**Pull request closed without merging**
